config/routes.rb
Rails.application.routes.draw do
  get 'nutritionists/search', action: :index, controller: :nutritionists
  get 'nutritionists/new'
  post 'nutritionists/create'

  root 'nutritionists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nutritionist.rb
class Nutritionist < ApplicationRecord
  has_and_belongs_to_many :tags
  has_one_attached :avatar
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :nutritionists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nutritionists_controller.rb
class NutritionistsController < ApplicationController
  def index
    search_param = params[:search_param]
    location = params[:location]
    @nutritionists = if search_param or location
        where_clause = "tags.name ILIKE ? OR nutritionists.name ILIKE ? OR clinic ILIKE ?"
        # split the search params into words with % signs for ILIKE matching
        param_list = search_param.split.map { |n| "%#{n}%" }
        # make a where clause for each of the words in the search params
        sql = param_list.map { where_clause }.join(" OR ")
        # triplicate each param to match the where clause
        param_list = param_list.flat_map { |n| [n, n, n] }
        # add the sql code to the begining of the list
        param_list.prepend(sql)
        location = "%#{location}%"
        Nutritionist
          .left_joins(:tags)
          .distinct
          .where(param_list)
          .where(["city ILIKE :l OR street ILIKE :l", l: location])
      else
        Nutritionist.all
      end
  end

  def new; end

  def create
    @nutr = Nutritionist.new(nutr_params)
    params[:nutritionist][:tags]&.split
      .map(&:downcase)
      .map { |t| Tag.find_or_create_by(name: t) }
      .each { |t| @nutr.tags << t }
    if @nutr.save
      render "new"
    else
      render "index"
    end
  end

  private

  def nutr_params
    params.require(:nutritionist).permit(
      :name,
      :number,
      :clinic,
      :street,
      :city,
      :personal_page,
      :price,
      :avatar,
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nutritionists_helper.rb
module NutritionistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EsmeraldasEmAutoestradas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <a href="/" class="logo"><%= image_tag 'logo.svg', :style => "height: 45px" %></a>
      <a class="signup" href="/">
        <button class="signup">
          Are you a healthcare professional? <strong>Sign up here</strong>
          <%= image_tag 'right_arrow_long.svg', :height => "25px", :class => "signup-arrow" %>
        </button>
      </a>
    </header>
    <%= yield %>
  </body>
</html>

app/views/nutritionists/index.html.erb
<div class="search-form">
  <%= form_with method: "get", local: true, :class => "search-form" do |f| %>
    <div class="search-box-div">
      <%= f.text_field :search_param,
        value: params[:search_param],
        placeholder: "Nutricionista Desportivo...",
        :class => "search-box-search" %>
    </div>
    <div class="search-box-div">
      <%= f.text_field :location,
        value: params[:location],
        placeholder: "Localização",
        :class => "search-box-location"  %>
    </div>
    <div class="search-box-div">
      <%= f.submit "Pesquisar", :class => "search-button" %>
    </div>
  <% end %>
</div>
<div class="nutritionists">
  <% @nutritionists.each do |n| %>
    <div class="nutritionist">
      <div class="nutritionist-img">
        <% if n.avatar.attached? %>
          <%= image_tag n.avatar, :class => "nutritionist-avatar" %>
        <% else %>
          <%= image_tag "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fhumancoders-formations.s3.amazonaws.com%2Fuploads%2Fcourse%2Flogo%2F1%2Fformation-ruby-on-rails.png", :class => "nutritionist-avatar" %>
        <% end %>
      </div>
      <div>
        <div class="upper-half">
          <div class="nutritionist-info">
            <p class="green-accent"><%= n.name %></p>
            <p class="orange-accent">Nutricionista - <%= n.number %></p>
          </div>
          <div class="nutr-buttons">
            <a href=""><button class="marcar-consulta orange-accent">Marcar consulta</button></a><br>
            <a href="<%= n.personal_page %>"><button class="pagina-pessoal green-accent">Página Pessoal</button></a>
          </div>
        </div>
        <div class="lower-half">
          <div class="nutritionist-location"> <!-- left side -->
            <div>
              <%= image_tag 'pin_hollow.svg', :width => "20px" %>
            </div>
            <div>
              <p class="green-accent">
              <%= n.clinic %>
              </p>
              <p><%= n.street %></p>
              <p><%= n.city %></p>
            </div>
          </div>
          <div class="booking">
            <div class="booking-icons">
              <%= image_tag 'case.svg', :class => "booking-icons", :width => "20px" %>
              <div class="dropdown">
                <button class="dropbtn">
                  Consulta domiciliar
                  <%= image_tag 'down_arrow.svg', :style => "padding-left:10px", :width => "10px" %>
                </button>
                <div class="dropdown-content">
                  <a href="#">Consulta consultório</a>
                </div>
              </div>
            </div>
            <div class="booking-icons">
              <%= image_tag 'money.svg', :class => "booking-icons", :width => "20px" %>
              <%= n.price %>€
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="pagination">
  <div class="pagination-inner">
    <div class="pagination-page"><a href="#">1</a></div>
    <div class="pagination-page"><a href="#">2</a></div>
    <div class="pagination-page"><a href="#">3</a></div>
    <div class="pagination-page selected"><a href="#">4</a></div>
    <div class="pagination-page"><a href="#">5</a></div>
    <div class="pagination-page"><a href="#">6</a></div>
    <div class="pagination-page"><a href="#">7</a></div>
    <div class="pagination-page"><a href="#">8</a></div>
    <div class="pagination-page"><a href="#">9</a></div>
    <div class="pagination-page"><a href="#">10</a></div>
    <div class="pagination-right">
      <%= image_tag 'right_arrow.svg' %>
    </div>
  </div>
</div>

app/views/nutritionists/new.html.erb
<h1> Add nutritionist </h1>
<%= form_with scope: :nutritionist, url: nutritionists_create_path, local: true do |form| %>
  <p>
  <%= form.label :name %>
  <%= form.text_field :name %>
  </p>
  <p>
  <%= form.label :number %>
  <%= form.text_field :number %>
  </p>
  <p>
  <%= form.label :clinic %>
  <%= form.text_field :clinic %>
  </p>
  <p>
  <%= form.label :street %>
  <%= form.text_field :street %>
  </p>
  <p>
  <%= form.label :city %>
  <%= form.text_field :city %>
  </p>
  <p>
  <%= form.label :personal_page %>
  <%= form.text_field :personal_page %>
  </p>
  <p>
  <%= form.label :price %>
  <%= form.text_field :price %>
  </p>
  <p>
  <%= form.label :avatar %>
  <%= form.file_field :avatar %>
  </p>
  <p>
  <%= form.label :tags %>
  <%= form.text_field :tags %>
  </p>
  <p> <%= form.submit :create %> </p>
<% end %>